Your Printer Name:
  title: "Daedelus"
  description: "CoreXY with swapable toolhead"
  repository: "https://raw.githubusercontent.com/meowkewok/Daedelus/refs/heads/main/JOURNAL.md"
  file_name: Daedelus.md
